apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-service
spec:
  selector:
    name: application
    stage: dev
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-application-service-public
# spec:
#   selector:
#     name: application
#     stage: dev
#     release: {{ .Release.Name }}
#   type: LoadBalancer
#   ports:
#     - port: {{ .Values.ports.public }}
#       targetPort: 80
